### ISSUE TITLE
503 Error: API TypeError

### ISSUE THREAD

**Issue by timmmmyboy** [ManifoldScholar/manifold-docker-compose#1]
Giving the Docker beta a swing and hit a roadblock. Compose seems to start everything properly but frontend is throwing the error 503 Error:
API TypeError
Failed to fetch

<img width="1152" alt="Screen Shot 2019-05-15 at 9 27 16 AM" src="https://user-images.githubusercontent.com/3890972/57779212-a93d2d00-76f3-11e9-91ba-989bed83cd63.png">

Let me know if there's anything I can dig into in the logs to assist with troubleshooting.

**Comment by zdavis** [comment]
Also, transferring this issue to manifoldScholar/manifold-docker-compose

**Comment by timmmmyboy** [comment]
Ah apologies, didn't realize there was a separate repo. Yes, unfortunately it does seem to persist. For reference I am using a Digital Ocean image with Docker pre-installed. `docker-compose restart` shows everything starting there. When you load the site you very briefly get the homepage with some broken images before the error takes over. I can also create a user with the docker exec functions (though I did have to use the name manifold-docker-compose_api_rails_1 as opposed to the documentation of just compose_api_rails_1)

**Comment by zdavis** [comment]
Well heck. I'll spin up a digital ocean env and see if I can reproduce. I've been testing on docker for mac.

ZD

**Comment by zdavis** [comment]
Before you run docker-compose and spin up the containers, you'll need to set a few things in environment/manifold.env

At the top of that file, you'll see three vars that need to be changed:

```
DOMAIN=127.0.0.1:4000

CLIENT_BROWSER_API_URL=http://127.0.0.1:4000
CLIENT_BROWSER_API_CABLE_URL=http://127.0.0.1:4000/cable
```

If you don't have a FQDN for the server and just want to use the IP address, you'll need to replace `127.0.0.1` with the IP of your droplet.

You'll need to make this change before running `docker-compose up`. If you already have the containers running, destroy them with `docker-compose down`, then make the change, then spin them back up.

**Comment by zdavis** [comment]
I should also add that serving content over ports 80 and 443 is commented out currently in the docker-compose.yml file, and you may want to uncomment those if you're serving it from a droplet. I will update the instructions to make some of this more clear—I had it setup more for running locally out-of-the-box.  With these changes, I was able to get it running on a droplet pretty easily: http://198.211.103.47/

**Comment by timmmmyboy** [comment]
Worked like a charm, thanks!

**Comment by zdavis** [comment]
Sweet!
